name: "Base Setup"
description: "Base Setup Actions Used Across Workflows"
inputs:
  python_version:
    description: "The python version"
  node_version:
    description: "The node version"
  dependency_type:
    default: "standard"
    description: "The dependency installation type: standard, pre, minimum"
runs:
  using: "composite"
  steps:
    - name: Set up environment
      shell: bash
      run: |
        set -eux
        PYTHON_VERSION="${{ inputs.python_version || matrix.python-version }}"
        NODE_VERSION=${{ inputs.node_version || matrix.node-version || '24.x' }}
        DEPENDENCY_TYPE=${{ inputs.dependency_type }}

        # Handle default python value based on dependency type.
        if [ $DEPENDENCY_TYPE == "pre" ]; then
          DEFAULT_PYTHON="3.13"
        elif [ $DEPENDENCY_TYPE == "minimum" ]; then
          DEFAULT_PYTHON="3.9"
        elif [ $DEPENDENCY_TYPE != "standard" ]; then
          echo "Unrecognized dependency type $DEPENDENCY_TYPE"
          exit 1
        else
          DEFAULT_PYTHON="3.12"
        fi

        echo "DEFAULT_PYTHON is $DEFAULT_PYTHON"
        PYTHON_VERSION="${PYTHON_VERSION:-$DEFAULT_PYTHON}"

        echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
        echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
        echo "CACHE_PREFIX=${{ runner.os }}-${{ github.workflow}}-${{ github.job }}" >> $GITHUB_ENV
        echo "DEPENDENCY_TYPE=$DEPENDENCY_TYPE" >> $GITHUB_ENV

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        allow-prereleases: true

    # Cache pip
    # We cannot use the builtin cache because it errors out with the files
    # are not present.
    - name: Get pip cache dir
      id: pip-cache
      shell: bash
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ env.CACHE_PREFIX }}-pip-${{ env.PYTHON_VERSION }}-${{ hashFiles('setup.cfg', 'setup.py', '**/requirements.txt', '**/pyproject.toml') }}
        restore-keys: |
          ${{ env.CACHE_PREFIX }}-pip-${{ env.PYTHON_VERSION }}

    - name: Detect package manager
      id: detect-pm
      shell: bash
      run: |
        if [ -f pnpm-lock.yaml ]; then
          echo "manager=pnpm" >> $GITHUB_OUTPUT
        elif [ -f yarn.lock ]; then
          echo "manager=yarn" >> $GITHUB_OUTPUT
        elif [ -f package-lock.json ]; then
          echo "manager=npm" >> $GITHUB_OUTPUT
        fi

    - name: Install pnpm
      if: steps.detect-pm.outputs.manager == 'pnpm'
      uses: pnpm/action-setup@v4

    - name: Enable corepack
      if: steps.detect-pm.outputs.manager == 'yarn'
      shell: bash
      run: |
        # Enable corepack if the project defines packageManager
        if [ -f package.json ]; then
          HAS_PKG_MANAGER=$(grep -e \"packageManager\"\: package.json || true)
          if [ ! -z "$HAS_PKG_MANAGER" ]; then corepack enable; fi
        fi

    - name: Install node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: ${{ steps.detect-pm.outputs.manager }}
        cache-dependency-path: |
          **/package-lock.json
          **/yarn.lock
          **/pnpm-lock.yaml

    - name: Cache checked links
      if: ${{ matrix.group == 'link_check' }}
      uses: actions/cache@v4
      with:
        path: ~/.cache/pytest-link-check
        key: ${{ env.CACHE_PREFIX }}-linkcheck-${{ hashFiles('**/*.md', '**/*.rst') }}-links
        restore-keys: |
          ${{ env.CACHE_PREFIX }}-linkcheck-

    - name: Cache conda
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: ${{ env.CACHE_PREFIX  }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('**/environment*.yml') }}
        restore-keys: |
          ${{ env.CACHE_PREFIX }}-conda-

    - name: Enable long paths on Windows
      if: startsWith(runner.os, 'Windows')
      run: Set-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem -Name LongPathsEnabled -Value 1
      shell: pwsh

    - name: Upgrade packaging dependencies
      shell: bash
      run: |
        set -eux
        echo "::group::Upgrade packaging dependencies"
        python -m pip install --upgrade pip pipx
        if [ "$RUNNER_OS" != "Windows" ]; then
          pipx install hatch --python $(which python)
        else
          pipx install hatch
        fi
        echo "::endgroup::"

    - name: Handle dependency type
      shell: bash
      run: |
        set -eux
        if [ $DEPENDENCY_TYPE == 'pre' ]; then
          echo "PIP_PRE=1" >> $GITHUB_ENV
        elif [ $DEPENDENCY_TYPE == 'minimum' ]; then
          source ${{ github.action_path }}/setup_constraints.sh
        fi

    - name: Print Diagnostics
      shell: bash
      run: |
        set -eux
        echo "::group::env"
        env
        echo "::endgroup::"
        pip debug || true
        echo "::group::piplist"
        pip list || true
        echo "::endgroup::"
        node --version
        npm --version || true
        yarn --version || true
        pnpm --version || true
