name: "Make an sdist"
runs:
  using: "composite"
  steps:
    - name: Build SDist
      shell: bash
      run: |
        pip install build
        python -m build --sdist
    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: "sdist"
        path: dist/*.tar.gz
