name: "Make an sdist"
runs:
  using: "composite"
  steps:
    - name: Build SDist
      shell: bash
      run: |
        pip install build
        python -m build --sdist
    - uses: actions/upload-artifact@v3
      with:
        name: "sdist"
        path: dist/*.tar.gz
