name: "Upload Coverage"
description: "Upload the coverage report(s) for this job"

inputs:
  # Optional inputs
  artifact_name:
    description: The artifact name - useful if multiple artifacts are created
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Rename coverage file
      shell: bash
      run: |
        if [ -f ".coverage" ]; then
          mv .coverage ".coverage.-$$-$RANDOM"
        fi
    - name: Handle artifact name
      id: artifact-name
      shell: bash
      run: |
        export name=${{ inputs.artifact_name }}
        if [ -z "$name" ]; then
          export name="coverage-$RANDOM"
        fi
        echo "artifact_name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"
    - name: Upload coverage data
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact-name.outputs.artifact_name }}
        path: ".coverage.*"
        if-no-files-found: ignore
