name: "Upload Coverage"
description: "Upload the coverage report(s) for this job"

runs:
  using: "composite"
  steps:
    - name: Rename coverage file
      shell: bash
      run: |
        if [ -f ".coverage" ]; then
          mv .coverage ".coverage.-$$-$RANDOM"
        fi
    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: coverage-data
        path: ".coverage.*"
        if-no-files-found: ignore
