name: "Enforce Labels"
description: "Enforce assigning triage labels before merging PRs"
runs:
  using: "composite"
  steps:
    - name: sleep-if-needed
      shell: bash
      if: ${{ github.event.action == 'opened' }}
      run: sleep 60
    - name: enforce-triage-label
      uses: actions/github-script@v3
      with:
        script: |
          const required = ['bug', 'enhancement', 'feature', 'maintenance', 'documentation'];
          const botUsers =['pre-commit-ci', 'dependabot'];
          const response = await github.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          let found = false;
          response.data.labels.forEach(label => {
            if (required.includes(label.name)) {
              found = true;
              console.log(`Found matching label "${label.name}"!`)
            }
          });
          if (!found) {
            // Try to automatically add maintenance label for known bot users
            try {
              if (botUsers.indeOf(response.data.user.login) !== -1) {
                octokit.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: ['maintenance']
                })
            } catch (e) {
              console.error(e);
            }

            console.error('Select at least one triage label:')
            console.error(required)
            process.exit(1)
          }
