name: "Test Sdist"
description: "Test a built sdist"
inputs:
  package_spec:
    description: "The package spec to install"
    default: '--editable ."[test]"'
    required: true
  test_command:
    description: "The test command"
    default: "python -m pytest -vv -raXxs --durations 10 --color=yes"
    required: true
  extra_test:
    description: "Optional extra test to run"
  env_values:
    description: "Optional env values to set for test, e.g. 'FOO=BAR FIZZ=BUZZ'"
runs:
  using: "composite"
  steps:
    - name: Download sdist
      uses: actions/download-artifact@v4
    - name: Install From SDist
      shell: bash
      run: |
        echo "::group::Install from SDist"
        set -ex
        cd sdist
        mkdir test
        tar --strip-components=1 -zxvf *.tar.gz -C ./test
        cd test
        python -m pip install ${{inputs.package_spec}}
        echo "::endgroup::"
    - name: Run Test
      shell: bash
      run: |
        echo "::group::Run test"
        set -ex
        cd sdist/test
        eval "${{inputs.env_values}}"
        eval "${{inputs.test_command}}"
        eval "${{inputs.extra_test}}"
        echo "::endgroup::"
