name: "Test Sdist"
description: "Test a built sdist"
inputs:
  package_spec:
    description: "The package spec to install"
    default: '--editable ."[test]"'
    required: true
  test_command:
    description: "The test command"
    default: "python -m pytest -vv -raXxs --durations 10 --color=yes"
    required: true
  extra_test:
    description: "Optional extra test to run"
  env_values:
    description: "Optional env values to set for test, e.g. 'FOO=BAR FIZZ=BUZZ'"
runs:
  using: "composite"
  steps:
    - name: Download sdist
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
    - name: Install From SDist
      shell: bash
      run: |
        echo "::group::Install from SDist"
        set -ex
        cd sdist
        mkdir test
        tar --strip-components=1 -zxvf *.tar.gz -C ./test
        cd test
        python -m pip install ${INPUTS_PACKAGE_SPEC}
        echo "::endgroup::"
      env:
        INPUTS_PACKAGE_SPEC: ${{inputs.package_spec}}
    - name: Run Test
      shell: bash
      run: |
        echo "::group::Run test"
        set -ex
        cd sdist/test
        eval "${INPUTS_ENV_VALUES}"
        eval "${INPUTS_TEST_COMMAND}"
        eval "${INPUTS_EXTRA_TEST}"
        echo "::endgroup::"
      env:
        INPUTS_ENV_VALUES: ${{inputs.env_values}}
        INPUTS_TEST_COMMAND: ${{inputs.test_command}}
        INPUTS_EXTRA_TEST: ${{inputs.extra_test}}
