name: "Report Coverage"
description: "Combine Coverage and Report"
inputs:
  fail_under:
    description: "The coverage amount to fail under"
    default: "80"
  artifact_pattern:
    description: ""
    required: false
    default: coverage-*

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        # Use latest Python, so it understands all syntax.
        python-version: "3.13"
        allow-prereleases: true

    - run: python -Im pip install --upgrade coverage[toml]
      shell: bash

    - name: Merge Artifacts
      uses: actions/upload-artifact/merge@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: coverage-data
        pattern: ${{ inputs.artifact_pattern }}
        delete-merged: true
        include-hidden-files: true

    - name: Combine coverage & fail if it's <${{inputs.fail_under}}.
      shell: bash
      run: |
        set -eux
        python -Iim coverage combine || true
        python -Iim coverage html --skip-covered --skip-empty

        # Report and write to summary.
        python -Iim coverage report | sed 's/^/    /' >> $GITHUB_STEP_SUMMARY

        # Report again and fail if under threshold
        python -Iim coverage report --fail-under=${INPUTS_FAIL_UNDER}
      env:
        INPUTS_FAIL_UNDER: ${{inputs.fail_under}}

    - name: Upload HTML report if check failed.
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: html-report
        path: htmlcov
      if: ${{ failure() }}
